### ISSUE TITLE
plot_coverage parameters

### ISSUE THREAD

**Issue by ManuelVelarde2212** [epiverse-trace/vaccineff#93]
**Hello, I want to know why the unit parameter in the plot_coverage function was deprecated.**
I was reviewing a  [publication of RPubs](https://rpubs.com/tracelac/vaccineff-testing) where I knew this project and when I replicated it I discovered that the plot_coverage function was refactored, everything was fine until I noticed that units can no longer be used.

I think it would be good to reconsider this change and recover the units parameter as it was:
unit = c(“day”, “month”, “year”), because it was very useful.

If not, please let me know why it is no longer available.

**Comment by ManuelVelarde2212** [comment]
I was looking at the rest of the [publication of RPubs](https://rpubs.com/tracelac/vaccineff-testing) and noticed that I am not able to use other functions as get_immunization_date, set_status, get_time_to_event, plot_survival or coh_eff_noconf.
Why do that functions are not exported to be used?

**Comment by davidsantiagoquevedo** [comment]
Hello @ManuelVelarde2212. Thanks for your interest in our package! You can still access all the functions presented in [Taller de evaluación de efectividad de vacunas con diseño de cohorte poblacional mediante vaccineff](https://rpubs.com/tracelac/vaccineff-testing) using version [v0.0.1](https://github.com/epiverse-trace/vaccineff/tree/v0.0.1) of `{vaccineff}`. To install it, please run the following code on your computer:
```
# First, uninstall any version you already have installed 
remove.packages("vaccineff")

# Install vaccineff 0.0.1
pak::pak("epiverse-trace/vaccineff@v0.0.1")
```

Since `{vaccineff}` is at an experimental stage of development, you will find a lot of differences between versions. I also recommend having a look at the new version [v0.0.4](https://github.com/epiverse-trace/vaccineff/tree/v0.0.4), for which we enhanced usability by masking many of the functions in `v0.0.1` using `S3 objects`. We deprecated the units in this version because of a bug induced by the new version of the `{scales}` package. Note that `plot_coverage()` will also be deprecated in `v0.0.5` (under preparation) and absorbed by the `plot` method of the `vaccineff_data` object (see Issue #85). Detailed documentation and explanations for the package are available in the vignette for [Cohort Designs](https://epiverse-trace.github.io/vaccineff/articles/cohort_design.html). To install it, follow a similar procedure as above, but replace the version with `v0.0.4`.

**Comment by ManuelVelarde2212** [comment]
Thank you very much, the answer cleared up all my doubts. Congratulations and keep up the good work. I will be happy to see how the project progresses.
